version: "3.3"
    
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: justwp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - chernyshov_db:/var/lib/mysql
      - ./db_dumb:/docker-entrypoint-initdb.d/
    restart: always
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - 8093:80
    volumes:
      - ./wordpress:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: justwp
volumes:
  chernyshov_db:
